version: '3.4'

services:
  couchbase: 
    image: couchbase:enterprise-6.0.3
    volumes:
    - "./couchbase:/opt/couchbase/var" # local folder where couchbase data stored 
    ports:
    - "8091:8091" # Allows local access to mgmt UI
  hellomicroservice:
    image: ${DOCKER_REGISTRY-}hellomicroservice
    build:
      context: .
      dockerfile: HelloMicroservice/Dockerfile